FROM ubuntu:latest
RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
    python3-pip python3-setuptools python3-dev && rm -rf /var/lib/apt/lists/*

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

#set workdir
WORKDIR /flaskapp
COPY . /flaskapp

RUN pip3 install wheel
RUN pip3 install -r requirements.txt

CMD ["flask", "run", "-h", "0.0.0.0", "-p", "4787"]